# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: adlopez- <adloprub004@gmail.com>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/01/28 13:35:18 by adlopez-          #+#    #+#              #
#    Updated: 2026/01/28 13:35:20 by adlopez-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


sample:
	gcc src/sample.c -o example
# sin flags genera el formato deseado
# (ELF64 dinamico por defectp x84_64 Linux)




clean:
	rm -rf example